### ISSUE TITLE
Drinking perk does not display correctly

### ISSUE THREAD

**Issue by Nazrin720** [Dom3062/SydneyHUDFix#27]
Drinking perk (I don’t know how English spells this PERK, I guess it’s Stoic perk). It is not displayed correctly,Like the one in the picture, I joined the game after others have started. Switch from other equipment to Stoic perk, after being attacked after entering,There is no correct indication of sustained damage on health,But continuous damage can be seen on the armor value,I think it should be a bug. The other HUD related mods are only Better Assault Indicator.

![QQ截图20200712210702](https://user-images.githubusercontent.com/63951577/87247968-76263300-c489-11ea-925a-b236f59a8c17.png)

**Comment by Dom3062** [comment]
Working as designed.
This is a Vanilla feature.
